### ISSUE TITLE
Clarify wishlist schema

### ISSUE THREAD

**Issue by aplarson** [eashmore/goodgames#1]
Do users have multiple wishlists? If so, they'll need a title or some other attribute to identify them. If a user only has one wishlist, we don't need the table and can just have a join table from users to games. The games-wishlists association also seems like it should involve a join table rather than a foreign key on games.

**Comment by eashmore** [comment]
Users will only have one wishlist. I'll update my readme to use a join
table.

On Mon, Jun 8, 2015 at 11:31 AM, Andrew Larson <notifications@github.com>
wrote:

> Do users have multiple wishlists? If so, they'll need a title or some
> other attribute to identify them. If a user only has one wishlist, we don't
> need the table and can just have a join table from users to games.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eashmore/goodgames/issues/1>.
>



-- 
Eric Ashmore
edashmore@gmail.com
(714) 514-1672
